
CREATE DATABASE IF NOT EXISTS `cmritfeed`;

USE `cmritfeed`;

CREATE TABLE IF NOT EXISTS `club`(
`id` INT AUTO_INCREMENT PRIMARY KEY,
`title` VARCHAR(30) UNIQUE NOT NULL,
`description` MEDIUMTEXT NOT NULL,
`president` VARCHAR(30) NOT NULL,
`contact` VARCHAR(12) NOT NULL,
`lastmod` INT NOT NULL
)ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `event`(
`id` INT AUTO_INCREMENT PRIMARY KEY,
`title` VARCHAR(30) UNIQUE NOT NULL,
`description` VARCHAR(30) NOT NULL,
`location` VARCHAR(30) NOT NULL,
`attendcount` INT NOT NULL,
`time` INT NOT NULL,
`club` VARCHAR(30) NOT NULL,
`lastmod` INT NOT NULL
)ENGINE=InnoDB;
